[2016-09-13 18:25:34,555] [ERROR] [__main__-3024.log] [device_center_client.py:_connect:585]  [connect failed]
[2016-09-13 18:25:46,176] [ERROR] [__main__-3024.log] [device_center_client.py:_connect:585]  [connect failed]
